title: Noiseless signal
description: '"Vieta dziļdomīgai sarkastiskai piezīmei, kura klejo pa interneta prērijām"'
show_downloads: true
google_analytics: UA-105382955-1
theme: jekyll-theme-cayman
exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
plugins:
  - jekyll-feed
